name: RewardsPlugin
main: com.platinumcore.rewards.RewardsPlugin
version: 1.0.0
api-version: 1.20
description: Opens a rewards GUI with custom items.
commands:
  rewards:
    description: Open the rewards menu.
    usage: /<command>
    permission: rewards.use
permissions:
  rewards.use:
    description: Allows players to open the rewards menu.
    default: true

